/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Program.Principal;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author alex
 */
public class Admin extends javax.swing.JFrame {

    private Principal p;

    public Admin(Principal p) {
        this.p = p;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        agSucursal = new javax.swing.JButton();
        agEmpleado = new javax.swing.JButton();
        agCliente = new javax.swing.JButton();
        seeReports = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        guardar = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setForeground(new java.awt.Color(153, 153, 153));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setForeground(new java.awt.Color(153, 153, 153));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel31.setBackground(new java.awt.Color(0, 0, 0));
        jLabel31.setForeground(new java.awt.Color(153, 153, 153));
        jLabel31.setText(" ");
        jPanel14.add(jLabel31, java.awt.BorderLayout.PAGE_START);

        jLabel32.setBackground(new java.awt.Color(0, 0, 0));
        jLabel32.setForeground(new java.awt.Color(153, 153, 153));
        jLabel32.setText(" ");
        jPanel14.add(jLabel32, java.awt.BorderLayout.PAGE_END);

        jLabel33.setBackground(new java.awt.Color(0, 0, 0));
        jLabel33.setForeground(new java.awt.Color(153, 153, 153));
        jLabel33.setText("          ");
        jPanel14.add(jLabel33, java.awt.BorderLayout.LINE_END);

        jLabel34.setBackground(new java.awt.Color(0, 0, 0));
        jLabel34.setForeground(new java.awt.Color(153, 153, 153));
        jLabel34.setText("          ");
        jPanel14.add(jLabel34, java.awt.BorderLayout.LINE_START);

        jPanel38.setBackground(new java.awt.Color(0, 0, 0));
        jPanel38.setForeground(new java.awt.Color(153, 153, 153));
        jPanel38.setLayout(new java.awt.GridLayout(1, 6));

        agSucursal.setBackground(new java.awt.Color(0, 0, 0));
        agSucursal.setFont(new java.awt.Font("Courier 10 Pitch", 1, 12)); // NOI18N
        agSucursal.setForeground(new java.awt.Color(153, 153, 153));
        agSucursal.setText("AGREGAR SUCURSAL");
        agSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agSucursalActionPerformed(evt);
            }
        });
        jPanel38.add(agSucursal);

        agEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        agEmpleado.setFont(new java.awt.Font("Courier 10 Pitch", 1, 12)); // NOI18N
        agEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        agEmpleado.setText("AGREGAR EMPLEADO");
        agEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agEmpleadoActionPerformed(evt);
            }
        });
        jPanel38.add(agEmpleado);

        agCliente.setBackground(new java.awt.Color(0, 0, 0));
        agCliente.setFont(new java.awt.Font("Courier 10 Pitch", 1, 12)); // NOI18N
        agCliente.setForeground(new java.awt.Color(153, 153, 153));
        agCliente.setText("AGREGAR CLIENTE");
        agCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agClienteActionPerformed(evt);
            }
        });
        jPanel38.add(agCliente);

        seeReports.setBackground(new java.awt.Color(0, 0, 0));
        seeReports.setFont(new java.awt.Font("Courier 10 Pitch", 1, 12)); // NOI18N
        seeReports.setForeground(new java.awt.Color(153, 153, 153));
        seeReports.setText("REPORTES");
        seeReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeReportsActionPerformed(evt);
            }
        });
        jPanel38.add(seeReports);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel38.add(jPanel1);

        guardar.setBackground(new java.awt.Color(0, 0, 0));
        guardar.setFont(new java.awt.Font("Courier 10 Pitch", 1, 12)); // NOI18N
        guardar.setForeground(new java.awt.Color(153, 153, 153));
        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel38.add(guardar);

        jPanel14.add(jPanel38, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel14, java.awt.BorderLayout.PAGE_END);

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setForeground(new java.awt.Color(153, 153, 153));
        jLabel30.setText(" ");
        jPanel13.add(jLabel30, java.awt.BorderLayout.PAGE_START);

        table.setBackground(new java.awt.Color(0, 0, 0));
        table.setFont(new java.awt.Font("Courier 10 Pitch", 1, 12)); // NOI18N
        table.setForeground(new java.awt.Color(153, 153, 153));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table);

        jPanel13.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel13, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agSucursalActionPerformed
        p.getCtrlAdmin().agData("agSucursal");
    }//GEN-LAST:event_agSucursalActionPerformed

    private void agEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agEmpleadoActionPerformed
        p.getCtrlAdmin().agData("agEmpleado");
    }//GEN-LAST:event_agEmpleadoActionPerformed

    private void agClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agClienteActionPerformed
        p.getCtrlAdmin().agData("agCliente");
    }//GEN-LAST:event_agClienteActionPerformed

    private void seeReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeReportsActionPerformed
        p.getCtrlAdmin().openReports();
    }//GEN-LAST:event_seeReportsActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        p.getCtrlAdmin().savedInfo();
    }//GEN-LAST:event_guardarActionPerformed

    public JTable getTable() {
        return table;
    }

    public void setTable(JTable table) {
        this.table = table;
    }

    public JButton getAgCliente() {
        return agCliente;
    }

    public void setAgCliente(JButton agCliente) {
        this.agCliente = agCliente;
    }

    public JButton getAgEmpleado() {
        return agEmpleado;
    }

    public void setAgEmpleado(JButton agEmpleado) {
        this.agEmpleado = agEmpleado;
    }

    public JButton getAgSucursal() {
        return agSucursal;
    }

    public void setAgSucursal(JButton agSucursal) {
        this.agSucursal = agSucursal;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agCliente;
    private javax.swing.JButton agEmpleado;
    private javax.swing.JButton agSucursal;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton seeReports;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
