/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Program.Principal;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author alex
 */
public class Caja_V extends javax.swing.JFrame {

    private Principal p;

    public Caja_V(Principal p) {
        this.p = p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        listProductos = new javax.swing.JComboBox<>();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        codProd = new javax.swing.JTextField();
        jPanel34 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel35 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel36 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel37 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel39 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        cantProd = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jPanel44 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        nit = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        apellido = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        sucursal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombreEmp = new javax.swing.JLabel();
        apellidoEmp = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        codEmp = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        noFact = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fechFact = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        facturar = new javax.swing.JButton();
        jPanel46 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INGRESO POR BUSQUEDA DE PRODUCTO");
        jPanel3.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel19.setLayout(new java.awt.GridLayout(1, 3));

        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel16.setText("  ");
        jPanel20.add(jLabel16, java.awt.BorderLayout.PAGE_END);

        jPanel28.setLayout(new java.awt.BorderLayout());

        jLabel17.setText("   ");
        jPanel28.add(jLabel17, java.awt.BorderLayout.PAGE_END);

        jPanel29.setLayout(new java.awt.GridLayout(1, 3));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jPanel29.add(jPanel30);

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jPanel29.add(jPanel31);

        jButton14.setText("CARGAR");
        jPanel29.add(jButton14);

        jPanel28.add(jPanel29, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel28, java.awt.BorderLayout.CENTER);

        jPanel19.add(jPanel20);

        jPanel3.add(jPanel19, java.awt.BorderLayout.PAGE_END);

        jPanel22.setLayout(new java.awt.BorderLayout());

        jLabel9.setText("     ");
        jPanel22.add(jLabel9, java.awt.BorderLayout.LINE_START);

        jLabel12.setText("     ");
        jPanel22.add(jLabel12, java.awt.BorderLayout.LINE_END);

        listProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel22.add(listProductos, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel22, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel32.setLayout(new java.awt.GridLayout(6, 1));

        jPanel33.setLayout(new java.awt.BorderLayout());

        jLabel18.setText(" ");
        jPanel33.add(jLabel18, java.awt.BorderLayout.LINE_END);

        jLabel19.setText(" ");
        jPanel33.add(jLabel19, java.awt.BorderLayout.LINE_START);
        jPanel33.add(codProd, java.awt.BorderLayout.CENTER);

        jPanel32.add(jPanel33);

        jPanel34.setLayout(new java.awt.BorderLayout());

        jLabel13.setText("    ");
        jPanel34.add(jLabel13, java.awt.BorderLayout.LINE_END);

        jLabel14.setText("    ");
        jPanel34.add(jLabel14, java.awt.BorderLayout.LINE_START);

        jPanel16.setLayout(new java.awt.GridLayout(1, 3));

        jButton1.setText("7");
        jPanel16.add(jButton1);

        jButton2.setText("8");
        jPanel16.add(jButton2);

        jButton3.setText("9");
        jPanel16.add(jButton3);

        jPanel34.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel32.add(jPanel34);

        jPanel35.setLayout(new java.awt.BorderLayout());

        jPanel40.setLayout(new java.awt.BorderLayout());

        jLabel15.setText("    ");
        jPanel40.add(jLabel15, java.awt.BorderLayout.LINE_END);

        jLabel20.setText("    ");
        jPanel40.add(jLabel20, java.awt.BorderLayout.LINE_START);

        jPanel21.setLayout(new java.awt.GridLayout(1, 3));

        jButton4.setText("4");
        jPanel21.add(jButton4);

        jButton5.setText("5");
        jPanel21.add(jButton5);

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton6);

        jPanel40.add(jPanel21, java.awt.BorderLayout.CENTER);

        jPanel35.add(jPanel40, java.awt.BorderLayout.CENTER);

        jPanel32.add(jPanel35);

        jPanel36.setLayout(new java.awt.BorderLayout());

        jPanel41.setLayout(new java.awt.BorderLayout());

        jLabel21.setText("    ");
        jPanel41.add(jLabel21, java.awt.BorderLayout.LINE_END);

        jLabel22.setText("    ");
        jPanel41.add(jLabel22, java.awt.BorderLayout.LINE_START);

        jPanel23.setLayout(new java.awt.GridLayout(1, 3));

        jButton7.setText("1");
        jPanel23.add(jButton7);

        jButton8.setText("2");
        jPanel23.add(jButton8);

        jButton9.setText("3");
        jPanel23.add(jButton9);

        jPanel41.add(jPanel23, java.awt.BorderLayout.CENTER);

        jPanel36.add(jPanel41, java.awt.BorderLayout.CENTER);

        jPanel32.add(jPanel36);

        jPanel37.setLayout(new java.awt.BorderLayout());

        jPanel42.setLayout(new java.awt.BorderLayout());

        jLabel23.setText("    ");
        jPanel42.add(jLabel23, java.awt.BorderLayout.LINE_END);

        jLabel24.setText("    ");
        jPanel42.add(jLabel24, java.awt.BorderLayout.LINE_START);

        jPanel24.setLayout(new java.awt.GridLayout(1, 3));

        jButton10.setText("0");
        jPanel24.add(jButton10);

        jButton11.setText("P");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel24.add(jButton11);

        jButton12.setText(".");
        jPanel24.add(jButton12);

        jPanel42.add(jPanel24, java.awt.BorderLayout.CENTER);

        jPanel37.add(jPanel42, java.awt.BorderLayout.CENTER);

        jPanel32.add(jPanel37);

        jPanel39.setLayout(new java.awt.BorderLayout());

        jLabel25.setText("  ");
        jPanel39.add(jLabel25, java.awt.BorderLayout.PAGE_START);

        jLabel26.setText("     ");
        jPanel39.add(jLabel26, java.awt.BorderLayout.LINE_END);

        jLabel27.setText("     ");
        jPanel39.add(jLabel27, java.awt.BorderLayout.LINE_START);

        jPanel25.setLayout(new java.awt.GridLayout(2, 2));

        jPanel26.setLayout(new java.awt.BorderLayout());

        jLabel28.setText(" ");
        jPanel26.add(jLabel28, java.awt.BorderLayout.PAGE_END);

        jPanel45.setLayout(new java.awt.GridLayout(1, 2));

        jLabel29.setText("CANTIDAD");
        jPanel45.add(jLabel29);
        jPanel45.add(cantProd);

        jPanel26.add(jPanel45, java.awt.BorderLayout.CENTER);

        jPanel25.add(jPanel26);

        jPanel27.setLayout(new java.awt.GridLayout(1, 3));

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel27.add(jPanel43);

        jButton13.setText("ENTER");
        jPanel27.add(jButton13);

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel27.add(jPanel44);

        jPanel25.add(jPanel27);

        jPanel39.add(jPanel25, java.awt.BorderLayout.CENTER);

        jPanel32.add(jPanel39);

        jPanel2.add(jPanel32, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel15.setLayout(new java.awt.GridLayout(2, 1));

        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ELECTRONIC HOMES");
        jPanel17.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel17);

        jPanel18.setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NIT");
        jPanel5.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitActionPerformed(evt);
            }
        });
        jPanel6.add(nit, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NOMBRE");
        jPanel7.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel8.add(nombre, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("APELLIDO");
        jPanel9.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9);

        jPanel10.setLayout(new java.awt.BorderLayout());
        jPanel10.add(apellido, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel10);

        jPanel18.add(jPanel1);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jPanel11.setLayout(new java.awt.GridLayout(7, 1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SUCURSAL");
        jPanel11.add(jLabel6);

        sucursal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(sucursal);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("VENDEDOR");
        jPanel11.add(jLabel8);

        nombreEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(nombreEmp);

        apellidoEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(apellidoEmp);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CODIGO");
        jPanel11.add(jLabel11);
        jPanel11.add(codEmp);

        jPanel4.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridLayout(4, 1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("NO. FACTURA");
        jPanel12.add(jLabel7);

        noFact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel12.add(noFact);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("FECHA DE VENTA");
        jPanel12.add(jLabel10);

        fechFact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel12.add(fechFact);

        jPanel4.add(jPanel12);

        jPanel18.add(jPanel4);

        jPanel15.add(jPanel18);

        getContentPane().add(jPanel15, java.awt.BorderLayout.PAGE_START);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel31.setText(" ");
        jPanel14.add(jLabel31, java.awt.BorderLayout.PAGE_START);

        jLabel32.setText(" ");
        jPanel14.add(jLabel32, java.awt.BorderLayout.PAGE_END);

        jLabel33.setText("          ");
        jPanel14.add(jLabel33, java.awt.BorderLayout.LINE_END);

        jLabel34.setText("          ");
        jPanel14.add(jLabel34, java.awt.BorderLayout.LINE_START);

        jPanel38.setLayout(new java.awt.GridLayout(1, 4));

        facturar.setText("FACTURAR");
        jPanel38.add(facturar);

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel38.add(jPanel46);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("TOTAL");
        jPanel38.add(jLabel35);

        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("1000");
        jPanel38.add(total);

        jPanel14.add(jPanel38, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel14, java.awt.BorderLayout.PAGE_END);

        jLabel30.setText(" ");
        jPanel13.add(jLabel30, java.awt.BorderLayout.PAGE_START);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel13.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel13, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nitActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    public JTextField getApellido() {
        return apellido;
    }

    public void setApellido(JTextField apellido) {
        this.apellido = apellido;
    }

    public JLabel getApellidoEmp() {
        return apellidoEmp;
    }

    public void setApellidoEmp(JLabel apellidoEmp) {
        this.apellidoEmp = apellidoEmp;
    }

    public JTextField getNit() {
        return nit;
    }

    public void setNit(JTextField nit) {
        this.nit = nit;
    }

    public JTextField getNombre() {
        return nombre;
    }

    public void setNombre(JTextField nombre) {
        this.nombre = nombre;
    }

    public JLabel getNombreEmp() {
        return nombreEmp;
    }

    public void setNombreEmp(JLabel nombreEmp) {
        this.nombreEmp = nombreEmp;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JLabel apellidoEmp;
    private javax.swing.JTextField cantProd;
    private javax.swing.JLabel codEmp;
    private javax.swing.JTextField codProd;
    private javax.swing.JButton facturar;
    private javax.swing.JLabel fechFact;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> listProductos;
    private javax.swing.JTextField nit;
    private javax.swing.JLabel noFact;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreEmp;
    private javax.swing.JLabel sucursal;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
