/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Program.Principal;
import javax.swing.JButton;

/**
 *
 * @author Alex
 */
public class ReportesGUI extends javax.swing.JFrame {

    private Principal p;

    public ReportesGUI(Principal p) {
        initComponents();
        this.p = p;
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rProdMasV = new javax.swing.JButton();
        rClieMasGan = new javax.swing.JButton();
        rSucMasVen = new javax.swing.JButton();
        rProMasIng = new javax.swing.JButton();
        rSucMasIng = new javax.swing.JButton();
        rProdMasVenSuc = new javax.swing.JButton();
        rEmpMasVen = new javax.swing.JButton();
        rProMasIngSuc = new javax.swing.JButton();
        rEmpMasIng = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText(" ");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("  ");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jLabel3.setText("     ");
        jPanel1.add(jLabel3, java.awt.BorderLayout.LINE_END);

        jLabel4.setText("     ");
        jPanel1.add(jLabel4, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("REPORTES");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel5);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("   ");
        jPanel3.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jLabel7.setText("   ");
        jPanel3.add(jLabel7, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new java.awt.GridLayout(3, 3));

        rProdMasV.setBackground(new java.awt.Color(0, 0, 0));
        rProdMasV.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rProdMasV.setForeground(new java.awt.Color(255, 255, 255));
        rProdMasV.setText("10 PRODUCTOS MAS VENDIDOS");
        rProdMasV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rProdMasVActionPerformed(evt);
            }
        });
        jPanel4.add(rProdMasV);

        rClieMasGan.setBackground(new java.awt.Color(0, 0, 0));
        rClieMasGan.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rClieMasGan.setForeground(new java.awt.Color(255, 255, 255));
        rClieMasGan.setText("10 CLIENTES QUE MAS GANACIAS GENERAN");
        rClieMasGan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rClieMasGanActionPerformed(evt);
            }
        });
        jPanel4.add(rClieMasGan);

        rSucMasVen.setBackground(new java.awt.Color(0, 0, 0));
        rSucMasVen.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rSucMasVen.setForeground(new java.awt.Color(255, 255, 255));
        rSucMasVen.setText("3 SUCURSALES CON MAS VENTAS");
        rSucMasVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSucMasVenActionPerformed(evt);
            }
        });
        jPanel4.add(rSucMasVen);

        rProMasIng.setBackground(new java.awt.Color(0, 0, 0));
        rProMasIng.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rProMasIng.setForeground(new java.awt.Color(255, 255, 255));
        rProMasIng.setText("10 PRODUCTOS CON MAS INGRESOS");
        rProMasIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rProMasIngActionPerformed(evt);
            }
        });
        jPanel4.add(rProMasIng);

        rSucMasIng.setBackground(new java.awt.Color(0, 0, 0));
        rSucMasIng.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rSucMasIng.setForeground(new java.awt.Color(255, 255, 255));
        rSucMasIng.setText("3 SUCURSALES CON MAS INGRESOS");
        rSucMasIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSucMasIngActionPerformed(evt);
            }
        });
        jPanel4.add(rSucMasIng);

        rProdMasVenSuc.setBackground(new java.awt.Color(0, 0, 0));
        rProdMasVenSuc.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rProdMasVenSuc.setForeground(new java.awt.Color(255, 255, 255));
        rProdMasVenSuc.setText("5 PRODUCTOS MAS VENDIDOS POR SUCURSAL");
        rProdMasVenSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rProdMasVenSucActionPerformed(evt);
            }
        });
        jPanel4.add(rProdMasVenSuc);

        rEmpMasVen.setBackground(new java.awt.Color(0, 0, 0));
        rEmpMasVen.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rEmpMasVen.setForeground(new java.awt.Color(255, 255, 255));
        rEmpMasVen.setText("3 EMPLEADOS CON MAS VENTAS");
        rEmpMasVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEmpMasVenActionPerformed(evt);
            }
        });
        jPanel4.add(rEmpMasVen);

        rProMasIngSuc.setBackground(new java.awt.Color(0, 0, 0));
        rProMasIngSuc.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rProMasIngSuc.setForeground(new java.awt.Color(255, 255, 255));
        rProMasIngSuc.setText("5 PRODUCTOS CON MAS INGRESOS POR SUCURSAL");
        rProMasIngSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rProMasIngSucActionPerformed(evt);
            }
        });
        jPanel4.add(rProMasIngSuc);

        rEmpMasIng.setBackground(new java.awt.Color(0, 0, 0));
        rEmpMasIng.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rEmpMasIng.setForeground(new java.awt.Color(255, 255, 255));
        rEmpMasIng.setText("3 EMPLEADOS CON MAS INGRESOS");
        rEmpMasIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEmpMasIngActionPerformed(evt);
            }
        });
        jPanel4.add(rEmpMasIng);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rProdMasVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rProdMasVActionPerformed
        p.getCtrlRepo().launchReport("ProdMasV");
    }//GEN-LAST:event_rProdMasVActionPerformed

    private void rClieMasGanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rClieMasGanActionPerformed
        p.getCtrlRepo().launchReport("ClieMasGan");
    }//GEN-LAST:event_rClieMasGanActionPerformed

    private void rSucMasVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSucMasVenActionPerformed
         p.getCtrlRepo().launchReport("SucMasVen");
    }//GEN-LAST:event_rSucMasVenActionPerformed

    private void rEmpMasVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEmpMasVenActionPerformed
        p.getCtrlRepo().launchReport("EmpMasVen");
    }//GEN-LAST:event_rEmpMasVenActionPerformed

    private void rProMasIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rProMasIngActionPerformed
        p.getCtrlRepo().launchReport("ProMasIng");
    }//GEN-LAST:event_rProMasIngActionPerformed

    private void rProdMasVenSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rProdMasVenSucActionPerformed
       p.getCtrlRepo().launchReport("ProdMasVenSuc");
    }//GEN-LAST:event_rProdMasVenSucActionPerformed

    private void rProMasIngSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rProMasIngSucActionPerformed
        p.getCtrlRepo().launchReport("ProMasIngSuc");
    }//GEN-LAST:event_rProMasIngSucActionPerformed

    private void rEmpMasIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEmpMasIngActionPerformed
        p.getCtrlRepo().launchReport("EmpMasIng");
    }//GEN-LAST:event_rEmpMasIngActionPerformed

    private void rSucMasIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSucMasIngActionPerformed
       p.getCtrlRepo().launchReport("SucMasIng");
    }//GEN-LAST:event_rSucMasIngActionPerformed

    public JButton getrAFD() {
        return rEmpMasVen;
    }

    public JButton getrErrores() {
        return rProdMasV;
    }

    public JButton getrLexemas() {
        return rSucMasVen;
    }

    public JButton getrTokens() {
        return rClieMasGan;
    }

    public JButton getAnalisisSintactico() {
        return rProMasIng;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton rClieMasGan;
    private javax.swing.JButton rEmpMasIng;
    private javax.swing.JButton rEmpMasVen;
    private javax.swing.JButton rProMasIng;
    private javax.swing.JButton rProMasIngSuc;
    private javax.swing.JButton rProdMasV;
    private javax.swing.JButton rProdMasVenSuc;
    private javax.swing.JButton rSucMasIng;
    private javax.swing.JButton rSucMasVen;
    // End of variables declaration//GEN-END:variables
}
